# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

env:
  XCODE_VERSION: "15.3"
  
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-14
    
    steps:
    - name: Select Xcode Version
      run: |
        sudo xcode-select -switch /Applications/Xcode_"$XCODE_VERSION".app
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        xcodebuild \
          -scheme Resting \
          -sdk macosx14.4 \
          -destination 'platform=macOS' \
          test &&
        xcodebuild \
          -scheme Resting \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          test &&
        xcodebuild \
          -scheme Resting \
          -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (41mm),OS=10.4' \
          test &&
        xcodebuild \
          -scheme Resting \
          -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation) (at 1080p),OS=17.4' \
          test
        xcodebuild \
          -scheme Resting \
          -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=1.1' \
          test
