name: Swift

env:
  XCODE_VERSION: "26.6"

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_"$XCODE_VERSION".app
    - name: Print Swift version
      run: swift --version
    - name: Test package
      run: swift test
    - name: Build release matrix
      run: |
        swift build -c release
        xcodebuild -scheme Resting -destination 'platform=macOS' build
        xcodebuild -scheme Resting -destination 'generic/platform=iOS' build
        xcodebuild -scheme Resting -destination 'generic/platform=watchOS' build
        xcodebuild -scheme Resting -destination 'generic/platform=tvOS' build
        xcodebuild -scheme Resting -destination 'generic/platform=visionOS' build
